#  docker-compose for DEV!!!
version: '3.1'

services:
  mysql:
    image: mysql:8
    volumes:
      - db-data:/var/lib/mysql/:rw
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "127.0.0.1:3306:3306"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/dev/nginx/hosts:/etc/nginx/conf.d
      - ./docker/dev/nginx/logs:/var/log/nginx
    depends_on:
      - php

  php:
    build: docker/dev/php
    volumes:
      - ./drush:/var/www/html/drush
      - ./scripts:/var/www/html/scripts
      - ./web/sites/all/libraries:/var/www/html/web/sites/all/libraries
      - ./web/sites/all/modules/custom:/var/www/html/web/sites/all/modules/custom
      - ./web/sites/all/themes/custom:/var/www/html/web/sites/all/themes/custom
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
      - ./web/sites/default/settings.php:/var/www/html/web/sites/default/settings.php
    working_dir: /var/www/html
    environment:
      PHP_IDE_CONFIG: "serverName=xdebug-docker"
      XDEBUG_CONFIG: "client_host=host.docker.internal start_with_request=trigger log_level=0"
      XDEBUG_MODE: "debug"
      XDEBUG_SESSION: "PHPSTORM"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  solr:
    image: solr:7-slim
    ports:
      - "8983:8983"
    volumes:
      - db-index:/var/solr/:rw
    command:
      - solr-precreate
      - ntb

volumes:
  db-data:
  db-index:
