<?php

/**
 * Implementation of hook_node_view().
 */

function teaser_thumbnail_node_view($node, $view_mode, $langcode) {
	if ($node->type == 'page' && $view_mode == 'teaser') {
		$body = $node->content['body'][0]['#markup'];
//		preg_match_all ('/<img .+src="([^"]+)" [^>]+>/is', $body, $images);
		preg_match ('/<img.*?src="([^"]+)"[^>]+>/is', $body, $image);

		$newbody = preg_replace('/(<img[^>]+>)/is', '', $body);
		$imagepath = (isset($image[1])) ? $image[1] : '';

		$node->content['body'][0]['#markup'] = '<a href="' . url( 'node/' . $node->nid, array('alias' => false )) . '"><img src ="' . $imagepath . '" style="margin: 0px 5px 0px 0px; width: 20%; float: left;"></a>' . $newbody;
	}
}